library(stringr)
library(tidyr)
library(dplyr)
tree<-melt(mass_data,id=c("County","FIPS","State"))
tree<-distinct(tree)
tree$variable<-str_remove(tree$variable,"X..")  
tree$variable<-gsub(".","",tree$variable,fixed = TRUE) 
variable$variable<-str_remove_all(variable$variable,"%")
variable$variable<-str_remove(variable$variable,"#")
variable$variable<-str_remove(variable$variable,"-")
variable$variable<-gsub(" ","",variable$variable,fixed = TRUE)
variable<-unique(variable)

mass_ind<-merge(tree,variable,by="variable")
write.csv(mass_ind,"mass_ind.csv")
